name = "temp-email-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
TEMP_EMAIL_DOMAIN = "zerostore.tech"
ADMIN_USER_ID = "1462157376"
FALLBACK_EMAIL = "didit.pamuji@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "fc2573ff-11f7-478f-a67e-591d6fc853c8"
