name = "temp-email-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
TEMP_EMAIL_DOMAIN = "mail.domainmu.com"

[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "GANTI_DENGAN_DATABASE_ID_MU"
